pull_request_template.md

Starting with a baseline pull request template

Adding PR Templates

---

README.md

Add Code Climate Badges

---

cccm-backend/cccm-api/pom.xml
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/client/ClientsApiServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/lookup/FormTypesApiServiceImpl.java
cccm-backend/cccm-api/src/main/resources/Community Corrections Case Management API.postman_collection.json
cccm-backend/cccm-api/src/main/resources/application.properties
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/main/resources/cccm-env.postman_environment.json
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/AddClientTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/GetClientTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/GetClientsTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/UpdateClientTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/AddFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/GetFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/GetFormsTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/UpdateFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/lookup/GetFormTypesTest.java

Add mock data
Add postman collection
Update tests

Add mock data

---

cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/AddClientTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/AddFormTest.java

Remove rest assured example test to speed up test execution

Remove rest assured tests examples

---

.github/workflows/build-push.yml

- Needed to change branch name in action to "main"

updated branch name

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiServiceImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/GetFormTest.java

Update swagger
Update mock data
Update tests
Tested with postman/unit test

Update Model to Support Form.IO

---

cccm-backend/cccm-api/pom.xml
cccm-backend/cccm-api/sample_data.json
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/DataService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/DataServiceImpl.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/GetFormByIdTest.java

Add Data Service
Load data from json file
Add unit test
Add logging
Unit test and postman

Add Service Pull Data From File

---

cccm-backend/cccm-api/pom.xml
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/client/ClientsApiServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/error/CCCMError.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/error/CCCMErrorCode.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/error/CCCMException.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/error/CCCMExceptionHandler.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/DataService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/DataServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/sidecard/SideCardsApiImpl.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/error/CCCMExceptionHandlerTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/GetFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/GetFormsTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/GetFormByIdTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/GetSideCardsTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/sidecard/GetSideCardsTest.java

Add error handling
Update tests
postman and unit tests

Add Error Handling 

---

cccm-backend/cccm-api/pom.xml

Adding Jacoco

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/client/ClientsApiServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/error/CCCMExceptionHandler.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/lookup/FormTypesApiServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/sidecard/SideCardsApiImpl.java

Add general logging for application

Adding logging

---

.github/workflows/backend-coverage-report.yml

- Cbcccm 145 : created github workflow for generating jacoco test coverage report to send to code climate!

Cbcccm 145

---

.github/workflows/build-push.yml
.github/workflows/promote-image-to-env.yml

CBCCCM 153 - updated tagging with environment names and added test and prod

Cbcccm 153

---

.github/workflows/backend-build-push.yml
.github/workflows/backend-promote-image-to-env.yml
.github/workflows/frontend-build-push.yml
.github/workflows/frontend-promote-image-to-env.yml

- CBCCCM-155 - split up backend and frontend services in workflows

Cbcccm 155

---

.github/workflows/backend-coverage-report.yml
cccm-backend/cccm-api/pom.xml
cccm-backend/cccm-api/src/main/resources/application.properties

Remove maven config (Defaulted with quarkus)
Update directory for coverage xml
Add generated code exclusion

Fix Jacoco Coverage Reporting

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/client/ClientsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/lookup/FormTypesApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/lookup/LocationsApiImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/GetClientTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/GetClientsTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/AddFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/DeleteFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/GetFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/GetFormsTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/UpdateFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/lookup/GetLocationsTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/GetFormByIdTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/GetSideCardsTest.java

Add Locations endpoint
Add mock return
Add tests
Refactor file/class names
Update tests
Fix copy pasta
Achieve 100% coverage

Add Location Endpoint/Refactoring

---

README.md

From issue: https://github.com/bcgov/jag-community-corrections-case-management/issues/3
Documentation

Adding lyfecycle badge and basic structure

---

README.md

Remove extra bracket

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/AddFormTest.java

Adding log line

---

cccm-backend/cccm-api/src/main/resources/sampleFormData.json

Remove question

---

cccm-frontend/src/components/common/FormioFormInfo.vue
cccm-frontend/src/components/crna-cmp/crnaCmpForm.vue
cccm-frontend/src/components/crna-cmp/formSections/crnaCmpFormInfo.vue
cccm-frontend/src/components/crna-cmp/formSections/crnaCmpFormNavigation.vue

- Properly fixed the responsive issue.
Yes, locally and visually

Properly fixed the responsive issue

---

cccm-backend/cccm-api/src/main/resources/sampleFormData.json

Remove Marshmallow

---

.github/workflows/backend-build-push.yml
.github/workflows/frontend-build-push.yml

Vulnscanning

---

.github/workflows/backend-build-push.yml
.github/workflows/frontend-build-push.yml

- Updated github actions to include checks on the code that has changed. If the backend code was changed then the backend build image action will run if the frontend code has changed then the backend build image action will not run. etc

Action update

---

.github/workflows/backend-build-push.yml
.github/workflows/frontend-build-push.yml
cccm-backend/Dockerfile

- Looking at some of the vulnerabilities the scanner highlighted, I added an upgrade into our containers to add any patches that get created for the latest version of ubuntu - while the scanner will still say the problem exists the upgrade should take care of *some* of the vulnerabilities and overall keep the images more up to date. I also fixed the reporting issue the scanner was having with a workaround until the problem gets addressed in a new version of the scanner 

Vuln testing

---

cccm-frontend/package-lock.json
cccm-frontend/package.json

- Fixed cccm-front build error
Visually tested

Fixed the cccm-frontend build error

---

cccm-backend/cccm-api/src/main/resources/cccm-api.yaml

Update payload to match mockups
Add Alerts and Warrants

Update client profile

---

cccm-frontend/src/router/index.ts
cccm-frontend/src/views/Unauthorized.vue

- unauthorized access implementation
Visually

First draft of unauthorized access implementation

---

cccm-frontend/src/components/common/FormioClientSearch.vue
cccm-frontend/src/components/common/templateClientSearch.json

- Added soundex to clientSearch page
Visual test, console log checking

Added soundex, clientSearch payload

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/client/ClientsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/ClientMapper.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/Alert.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/ClientProfile.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/Photo.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ObridgeClientService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/SpeedmentClientService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/util/MappingUtils.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/GetClientPhotoTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/GetClientTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/model/AlertTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/model/ClientProfileTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/model/PhotoTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/util/CreateDesignationsTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/util/StringToWarrantListTest.java

Data access for client profile

Client profile api data access

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/client/ClientsApiImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/GetClientPhotoTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/util/StringToWarrantListTest.java

Adding photo endpoint

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/FormMapper.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/Form.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/SpeedmentClientService.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/GetFormSearchTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/model/FormTest.java

Adding form search functionality to support rna list 

Adding form search for rna list

---

cccm-backend/cccm-api/src/main/resources/cccm-api.yaml

Add missing field

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/lookup/FormTypesApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/lookup/LocationsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/CodeTableMapper.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/CodeTable.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/SpeedmentClientService.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/lookup/GetFormTypesTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/lookup/GetLocationsTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/model/CodeTableTest.java

Add Data Access For Lookups

---

cccm-frontend/src/views/RNAList.vue

- Fixed the RNA list filter logic
Visual inspection

Filter fix

---

cccm-frontend/src/views/DashboardPOView.vue

- PO dashboard small fixes
Visually tested

Defect fixes

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/client/ClientsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/service/ClientSearch.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/GetClientsTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/model/ClientSearchTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientSearchTest.java

Adding new fields
Adding search criteria to endpoint

PO Dashboard Support

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/client/ClientsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/dashboard/DashboardsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/ClientMapper.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/GetClientPhotoTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/dashboard/GetSupervisorDashboardTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientPhotoTest.java

Add supervisor dashboard endpoint (no dataaccess)
UPdate photo endpoint returns base64 string in object

Add supervisor endpoint

---

cccm-frontend/nginx.conf

- Attempt to fix the proxy issue
- [] Bug fix (non-breaking change which fixes an issue)
- [X ] My code follows the style guidelines of this project

Attempt to fix the proxy issue

---

cccm-frontend/tsconfig.json

Updated the baseUrl

---

cccm-frontend/nginx.conf
cccm-frontend/tsconfig.json

Reverted all the changes

---

cccm-frontend/index.html
cccm-frontend/src/components/Header.vue
cccm-frontend/vite.config.ts

Attempt to add root path

---

cccm-frontend/Dockerfile
cccm-frontend/index.html
cccm-frontend/nginx.conf
cccm-frontend/src/components/Header.vue
cccm-frontend/src/components/common/FormioClientSearch.vue
cccm-frontend/src/views/DashboardPOView.vue
cccm-frontend/src/views/DashboardSupervisorView.vue

- CBCCCM-313: Add root path (/cccm) to the frontend app

Implements root path to frontend app

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/client/ClientsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/service/ClientSearch.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ObridgeClientService.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/GetClientsTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/model/ClientSearchTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientSearchTest.java

Update api client search based on screen requirements

Client Search Updates

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/CodeTableMapper.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/lookup/GetAddressTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/lookup/GetFormTypesTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/lookup/GetGendersTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/lookup/GetIdentifiersTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/lookup/GetLocationsTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/codetable/GetCodeTableTest.java

Refactor code/description to key/value

Update to key/value

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/error/CCCMErrorCode.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/error/CCCMExceptionHandler.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/error/CCCMExceptionHandlerTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/AddQuestionAnswerTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/UpdateQuestionAnswerTest.java

Add form question adds and updates

Add Form Question Add and Updates

---

cccm-frontend/src/assets/css/layout.css
cccm-frontend/src/assets/css/overrides.css
cccm-frontend/src/assets/css/styles.css
cccm-frontend/src/views/DashboardPOView.vue

- css fixes for dashboard layout
Visually on localhost

cherry pick files from feature/fix-dashboard-layout - [DR]

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/ClientMapper.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/Client.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/util/MappingUtils.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientProfileTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientSearchTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/util/mapping/StringToAddressListTest.java

Adjust address functionality 
Move case manager bind location

Refactor for Case Manage and Address

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/UserDataService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/UserDataServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/user/UserApiImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/user/GetDefaultLocationTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/user/GetUserDefaultLocationTest.java

CBCCCM-320 - Add get default location endpoint

Add Default User Location Endpoint

---

cccm-frontend/src/assets/css/overrides.css
cccm-frontend/src/components/common/FormioClientSearch.vue
cccm-frontend/src/components/common/templateClientSearch.json

various css fixes for client search
Visually tested locally

variosu css fixes for client search page  - [DR]

---

.github/workflows/backend-build-push.yml
.github/workflows/frontend-build-push.yml

- In order for Argo cd to be in sync with openshift, an updated needed to be made to the kustomization file in our other repo upon image push from this repo. Updates were made to the github actions of this repo accordingly
Ran the github action a **lot** and verified in argo cd and openshift

Image trigger

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientSearchTest.java

Adding Address Search to Service

---

.github/workflows/backend-promote-image-to-env.yml
.github/workflows/frontend-promote-image-to-env.yml

- Promoting images to test (and prod) and updating their kustomization file according to whats deployed in openshift 
I tested out the action and verified it did what was expected in openshift and argocd

Image promoting

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/client/ClientsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/ClientMapper.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/Alert.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/ClientProfile.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/service/ClientAddressSearch.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/service/ClientSearch.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ObridgeClientService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/SpeedmentClientService.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/GetClientAddressSearchTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/GetClientPhotoTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/model/AlertTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/model/ClientAddressSearchTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/model/ClientProfileTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/model/ClientSearchTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientAddressSearchTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientPhotoTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientProfileTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientSearchTest.java

Add address search
Move alerts to obridge call
Refactoring

Adding Address Search and Implement Alerts

---

cccm-frontend/src/components/common/FormioClientSearch.vue
cccm-frontend/src/components/common/templateClientSearch.json

- CBCCCM-337: Update the client search to match the latest mockup design

cbcccm-337: client search updates

---

cccm-backend/cccm-api/src/main/resources/application.properties

Remove query params from access logs

Remove Query String From Log

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/CodeTableServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/FormDataServiceImpl.java
cccm-backend/cccm-api/src/main/resources/application.properties
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientPhotoTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientProfileTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/codetable/GetCodeTableTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/form/FormSearchTest.java

Delete speedment references

---

.github/workflows/backend-build-push.yml
.github/workflows/backend-promote-image-to-env.yml
.github/workflows/frontend-build-push.yml
.github/workflows/frontend-promote-image-to-env.yml

- added in image push to golddr after we build and push it to gold
- also updates the kustomization file in our other repo with the image changes so argocd is happy
I ran the actions on my branch and verified their functions in openshift/github

Golddrpush

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/client/ClientsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/user/UserApiImpl.java

Make api's request scoped

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/client/ClientsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/service/ClientAddressSearch.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/service/ClientSearch.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/GetClientAddressSearchTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/GetClientsTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/model/ClientAddressSearchTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/model/ClientSearchTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientAddressSearchTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientSearchTest.java

Update fields to match updated ux

Update API Fields

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/client/ClientsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/dashboard/DashboardsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/lookup/LookupApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/GetClientAddressSearchTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/GetClientPhotoTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/GetClientTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/GetClientsTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/dashboard/GetSupervisorDashboardTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/AddFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/AddQuestionAnswerTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/DeleteFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/GetFormByIdTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/GetFormByTypeTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/GetFormSearchTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/GetFormsTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/UpdateFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/UpdateQuestionAnswerTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/lookup/GetAddressTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/lookup/GetFormTypesTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/lookup/GetGendersTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/lookup/GetIdentifiersTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/lookup/GetUserLocationsTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientProfileTest.java

Adding Location to Request Header

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/ClientMapper.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/Client.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/util/MappingUtils.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/model/ClientTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientSearchTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/util/mapping/StringToAddressListTest.java

Adding missing search fields

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/ClientMapper.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/Photo.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/model/PhotoTest.java

Photo taken date

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/ClientMapper.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/GetClientDetailsTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientDetailsTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientProfileTest.java

Add photo to spec
Add photo to mapper
Remove current name field

Add Photo to Profile and Details

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/client/ClientsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/GetClientAddressTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/GetClientPhotoTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/GetClientTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/AddQuestionAnswerTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/model/AddressTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/model/AlertTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/user/GetDefaultLocationTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/user/GetLocationsTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/user/GetOracleIdTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/user/GetUserIdTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/user/GetUserLocationsTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/util/mapping/IsExpiredTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/util/mapping/StringToAddressListTest.java

Values were reversed when location was added. 

Fix Endpoint Data Bug

---

cccm-frontend/src/assets/css/overrides.css
cccm-frontend/src/components/ClientRecord.vue
cccm-frontend/src/components/DashboardPOView.vue
cccm-frontend/src/components/common/templateClientProfilePO.json

style fixes for dashboard po page with embedded client record
Visually on localhost

save style fixes for dashboard po page - [DR]

---

cccm-frontend/src/components/RNAList.vue

centre aligned colored cells in rna table.
Visually on localhost

vertical and center align rna colored cells - [DR]

---

cccm-frontend/src/assets/css/overrides.css
cccm-frontend/src/components/DashboardSupervisorView.vue

fixes footer styles for supervisor dashboard
Visually localhost

fix footer style of supervisor dashboard - [DR]

---

cccm-frontend/src/assets/css/overrides.css
cccm-frontend/src/components/sara-cmp/sampleData/saraSampleData.json
cccm-frontend/src/components/sara-cmp/saraCmpForm.vue

Style fixes for sara cmp form.
Visually on localhost

style fixes for sara-cmp - [DR]

---

cccm-frontend/src/components/RNAList.vue

fix status field and update date field to be center aligned in rnalis
Visually localhost

fix status field and update date field to be center aligned in rnalist - [DR]

---

cccm-frontend/src/assets/css/overrides.css
cccm-frontend/src/components/trendanalysis/ChartFilter.vue

various style fixes for trend analysis page
Visually tested on localhost

various styles fixes for ternd analysis - [DR]

---

cccm-frontend/index.html

Bug fix to change the reference to formio.full.min.js

Changed the reference to formio.full.min.js

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/dashboard/DashboardsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/UserMapper.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/PODashboard.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ObridgeClientService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/UserDataService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/UserDataServiceImpl.java
cccm-backend/cccm-api/src/main/resources/application.properties
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/dashboard/GetPODashboardTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/model/AddressTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/model/PODashboardTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/user/GetPoDashboardTest.java

PO Dashboard API Implementation

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/client/ClientsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/service/ClientAddressSearch.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/service/ClientSearch.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ObridgeClientService.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/GetClientAddressSearchTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/GetClientsTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/model/ClientAddressSearchTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/model/ClientSearchTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientAddressSearchTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientSearchTest.java

Sync Search With Procedure Update

Sync Search With Procedure Update

---

cccm-frontend/src/assets/css/overrides.css
cccm-frontend/src/components/Header.vue
cccm-frontend/src/components/common/FormioClientSearch.vue
cccm-frontend/src/components/common/templateClientSearch.json

- removes text shadow from header nav 
- reduces whitespace from client search 
- visually on localhost

remove textshadow from header nav, reduce whitepsace from client profile - [DR]

---

cccm-frontend/src/components/trendanalysis/ChartFilter.vue
cccm-frontend/src/components/trendanalysis/DataView.vue
cccm-frontend/src/components/trendanalysis/InterventionsTable.vue
cccm-frontend/src/components/trendanalysis/TrendChart.vue

- Fixed the dev-devtools issue

Updated the references to pinia

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/dashboard/DashboardsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/UserMapper.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/SupervisorDashboard.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ObridgeClientService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/UserDataService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/UserDataServiceImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/dashboard/GetSupervisorDashboardTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/user/GetSupervisorDashboardTest.java

Adding Supervisor Dashboard endpoint

Adding supervisor dashboard implementation

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-frontend/src/components/common/FormioSidePanel.vue
cccm-frontend/src/components/common/templateSidePanel.json
cccm-frontend/src/components/form.api.ts
cccm-frontend/src/components/form/FormRenderer.vue

- CBCCCM-452: Display and save sources contacted (frontend and API)

Display and save sourcesContacted

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/CloneFormRequest.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ObridgeClientService.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml

Add clone form endpoint
Add link and update 
Refactor

Add Clone/Link/Update Functionality

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/Keys.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/FormInput.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ObridgeClientService.java

Implement Saves

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-frontend/src/components/CmpForm.vue
cccm-frontend/src/components/common/FormioSidePanel.vue
cccm-frontend/src/components/common/templateSidePanel.json

- Typo fix to side panel
- Fix the sourceContacted update

Typo fix to side panel, fix to sourceContacted update

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/validation/Question.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/validation/Validation.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/validation/ValidationError.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/validation/ValidationResult.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ValidationService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ValidationServiceImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/main/resources/configs/clone_config.json
cccm-backend/cccm-api/src/main/resources/configs/crna_validation_config.json
cccm-backend/cccm-api/src/main/resources/configs/sara_validation_config.json

Add Validation Endpoint
Add Delete endpoint
Add partail validation implementation

Adding Validation and Delete

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/service/DeleteRequest.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ObridgeClientService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ValidationServiceImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml

Implement Delete

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml

Add endpoint to remove date and set completed flag to n

Add edit endpoint

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java

Changes to support form type implementation change

update to form type implementation

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml

Add form linkage after creation

Add Link Form Endpoint CBCCCM-413

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/dashboard/DashboardsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/UserDataService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/UserDataServiceImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/dashboard/GetSupervisorDashboardTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/user/GetSupervisorDashboardTest.java

Add locationid to request

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/dashboard/DashboardsApiImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml

Add supervisor details endpoint

Add supervisor details endpoint

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/UserDataServiceImpl.java

Change po dashboard implementation

Strip username directly

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ValidationServiceImpl.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/validation/ValidateSARATest.java

Validate Empty Answer Set

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/dashboard/DashboardsApiImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml

Add New Fields Supervisor

---

cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/main/resources/configs/sara_validation_config.json

re-add config

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/dashboard/DashboardsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/UserDataService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/UserDataServiceImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/dashboard/GetPODashboardTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/user/GetPoDashboardTest.java

Replace header location with request location

Add location id to endpoint

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientFormSearchTest.java

RNA List CRNA-SARA merge

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/ClientMapper.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/ClientProfile.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/model/ClientProfileTest.java

Fixing date issue

---

cccm-frontend/src/components/DashboardPOView.vue
cccm-frontend/src/components/RNAList.vue
cccm-frontend/src/main.ts

- Updating RNAList type filtering
- Fixed the form creation dialog checkbox 

Update RNAList type filtering

---

cccm-frontend/src/components/CmpForm.vue

Updated the formId once a SARA is created

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/Keys.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/Location.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ObridgeClientService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/UserDataService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/UserDataServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/user/UserApiImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/user/LogonUserTest.java

Add User Logon endpoint
Returns:
- Users Default Location
- Users Locations Refined By Type
Sets:
- Logon date

Add Logon Endpoint and Logic

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/Keys.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/Location.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ObridgeClientService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/UserDataService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/UserDataServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/user/UserApiImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/user/LogonUserTest.java

Add client number to request as it is required for client logs and rna list update

Add field required for log and rna update

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/Keys.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/Location.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ObridgeClientService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/UserDataService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/UserDataServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/user/UserApiImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientFormSearchTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/user/LogonUserTest.java

Add final two merge requirements

RNA List Merge Update

---

cccm-backend/cccm-api/src/main/resources/application.properties

Adding timeouts

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/FormInput.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/service/UpdateForm.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/CodeTableServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/trend/TrendApiImpl.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/CompleteFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/EditFormTest.java

Consolidate very similar logic 

Consolidate Edit/Complete

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/util/JwtUtils.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/util/jwt/StripUserNameTest.java

Due to SSO changes the @idir will not be present in the keycloak user

Handle switch to not using @idir

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/Keys.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/CompleteFormInput.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ObridgeClientService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/trend/TrendApiImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/CompleteFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/EditFormTest.java

Update endpoints to support new procedure

Update Edit and Complete 

---

cccm-frontend/public/config.js
cccm-frontend/src/plugins/authentication.js

- CBCCCM-514: Frontend Use IDP-HINT

Add idpHint to keycloak login options

---

cccm-backend/cccm-api/src/main/resources/configs/clone_config.json
cccm-backend/cccm-api/src/test/resources/configs/clone_config.json

Remove illogical clone ignores

Remove additional ignores

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/ClientMapper.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/util/MappingUtils.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/util/mapping/CalculateAgeTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/util/mapping/FormatDateTest.java

Ensure birth dates are handled in the different formats
Ensure Age calc handles different formats

Format Date and Fix Age Calc

---

cccm-frontend/public/config.js
cccm-frontend/src/components/form.api.ts

- CBCCCM-505: Timeouts: Frontend requests

Added axios timeout

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientFormSearchTest.java

Implement rating and supervision level logic.

Add supervision level and rating logic

---

cccm-backend/cccm-api/pom.xml
cccm-backend/pom.xml

Set Version to Match current sprint

Increment Version

---

cccm-frontend/src/components/form/FormRenderer.vue

- CBCCCM-532: RNA Initial Assessment comments and Reassessment Comments

CBCCCM-532: RNA Initial Assessment comments and Reassessment Comments

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/Keys.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/util/MappingUtils.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientFormSearchTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/GetClientFormSummaryTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/util/mapping/CalculateLockedTest.java

Add lock boolean 
Apply logic to set

Add Lock Boolean

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/Keys.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/util/MappingUtils.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientFormSearchTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/util/mapping/CalculateLockedTest.java

Adding acute to RNA List search
Update locked logic

Adding acute to RNA list

---

cccm-frontend/src/components/RNAList.vue
cccm-frontend/src/components/common/templateButtonGroupSubmit.json
cccm-frontend/src/components/trendanalysis/TrendAnalysisView.vue

- Fix logic to display saveContinue button

Fixed the condition logic for 'Save and Continue' button

---

cccm-frontend/src/components/CmpForm.vue
cccm-frontend/src/components/DashboardPOView.vue
cccm-frontend/src/components/DashboardSupervisorView.vue
cccm-frontend/src/components/Header.vue
cccm-frontend/src/components/RNAList.vue
cccm-frontend/src/components/common/FormioClientSearch.vue
cccm-frontend/src/components/form/FormRenderer.vue
cccm-frontend/src/main.ts

- Refactored hardcoded text
- Fixed the 'Edit' button behavior

Refactored hardcoded value; fixed the 'Edit' button behavior

---

cccm-backend/cccm-role-sync/pom.xml
cccm-backend/cccm-role-sync/src/main/java/ca/bc/gov/open/jag/CCCMRoleSync.java
cccm-backend/cccm-role-sync/src/main/resources/client/keycloak-openapi.yml

Update run and generate client code

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/role/RoleApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/role/service/RoleServiceImpl.java

Add missing annotation

---

cccm-frontend/src/assets/css/overrides.css
cccm-frontend/src/components/RNAList.vue
cccm-frontend/src/components/form/FormRenderer.vue

- CBCCCM-577: RNA Status: display only Incomplete and Complete (not Overdue)
_ CBCCCM-580: Add which RNAs are overdue to above RNA List

Added Overdue RNA form list, and it's styling

---

cccm-backend/cccm-role-sync/src/main/java/ca/bc/gov/open/jag/service/RoleSyncServiceImpl.java
cccm-backend/cccm-role-sync/src/main/resources/application.properties
cccm-backend/cccm-role-sync/src/test/java/ca/bc/gov/open/jag/service/RoleSyncServiceTest.java

Move to dependency injection
Implement test

Refactor and Add Test

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/Keys.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/ClientMapper.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/Client.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/util/MappingUtils.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/model/ClientTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientAddressTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientDetailsTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/util/mapping/IsExpiredTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/util/mapping/StringToAddressListTest.java

Add address type and status mapping

Adding type and status

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java

Add correct error type

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-role-sync/src/main/java/ca/bc/gov/open/jag/Keys.java
cccm-backend/cccm-role-sync/src/main/java/ca/bc/gov/open/jag/service/RoleSyncServiceImpl.java
cccm-backend/cccm-role-sync/src/test/java/ca/bc/gov/open/jag/service/RoleSyncServiceTest.java

Role Sync Update

---

cccm-backend/pom.xml

Add profiles to parent pom

---

cccm-frontend/src/components/RNAList.vue
cccm-frontend/src/components/common/FormioFormInfo.vue
cccm-frontend/src/components/form/FormRenderer.vue
cccm-frontend/src/components/form/formSections/FormDataEntry.vue
cccm-frontend/src/main.ts

- Code cleanup on refreshing auto calculated question answer

Code cleanup

---

cccm-frontend/src/components/CmpForm.vue
cccm-frontend/src/components/RNAList.vue
cccm-frontend/src/components/form/formSections/FormDataEntry.vue
cccm-frontend/src/main.ts
cccm-frontend/src/stores/autoSaveStore.js

- CBCCCM-608: Create the Static99R form type override file to support formio template saturation process
- CBCCCM-609: Frontend change to support Static99R form creation, searching

Added START99R

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/Keys.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ValidationService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ValidationServiceImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/main/resources/configs/clone_config.json
cccm-backend/cccm-api/src/main/resources/configs/static99r_validation_config.json
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/CompleteFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/CreateFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/EditFormTest.java

Adding backend implementations 

Static99r backend

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientFormSearchTest.java

Update From Search

---

cccm-backend/cccm-role-sync/src/main/java/ca/bc/gov/open/jag/service/RoleSyncServiceImpl.java

Set Enabled

---

cccm-frontend/src/components/Header.vue
cccm-frontend/src/components/Unauthorized.vue

- CBCCCM-126: Error Screen - "Authenticated but not Authorized"

Updated Unauthorized view, including the wording and layout

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/ClientMapper.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/ClientProfile.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/main/resources/configs/acute_validation_config.json
cccm-backend/cccm-api/src/main/resources/configs/clone_config.json
cccm-backend/cccm-api/src/main/resources/configs/static99r_validation_config.json
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientProfileTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/CloneFormTest.java
cccm-backend/cccm-api/src/test/resources/configs/clone_config.json

Add clone config
Add rna Status
Add acute validation config
Add static99r validation config

Adding RNA Status, Clone Configs and Acute/Static99r Validation

---

cccm-frontend/src/components/ClientRecord.vue
cccm-frontend/src/components/CmpForm.vue
cccm-frontend/src/components/RNAList.vue
cccm-frontend/src/components/form/FormRenderer.vue
cccm-frontend/src/main.ts

- CBCCCM-622: Select to create a Stable RNA

Feature/cbcccm 622 UI create stable form

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiImpl.java

Add Fine Grained Roles

---

cccm-frontend/src/components/DashboardPOView.vue
cccm-frontend/src/components/common/templateClientProfilePO.json

- CBCCCM-648: PO dashboard UI data mapping issue

FIxed the data mapping.

---

cccm-backend/cccm-api/src/main/resources/application.properties

Exclude health endpoint from access logs 

Exclude health from standard out

---

.github/workflows/role-sync-promote-image-to-env.yml
README.md

- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have made corresponding changes to the documentation
- [x ] New and existing unit tests pass locally with my changes

added CI/CD niotes

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/Keys.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/CloneFormRequest.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/CloneFormTest.java
cccm-backend/cccm-role-sync/src/main/java/ca/bc/gov/open/jag/service/RoleSyncServiceImpl.java

Added clone restriction logic
Added Federated identity logic on user update

Adding support of new role configs

---

cccm-backend/cccm-api/src/main/resources/cccm-api.yaml

Make Field Required In Dashboards

---

cccm-frontend/src/assets/css/overrides.css
cccm-frontend/src/components/DashboardPOView.vue
cccm-frontend/src/components/common/templateClientProfile.json
cccm-frontend/src/components/common/templateClientProfilePO.json

- CBCCCM-647: My (PO) Dashboard Testing Results

cbcccm-647: podashboard issues

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/service/ClientSearch.java

Swapped incorrectly mapped fields

Fix search issue

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java

Get answers from linked form id not parents

Fix Linked Form Validation

---

cccm-backend/cccm-api/src/main/resources/cccm-api.yaml

Convert to SORA

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/Keys.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ValidationService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ValidationServiceImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/main/resources/configs/clone_config.json
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/CompleteFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/CreateFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/validation/ValidateACUTETest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/validation/ValidateOVERALLTest.java

Refactor to SO-Overall

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/Keys.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/main/resources/configs/clone_config.json

Use Underscore

---

cccm-backend/cccm-api/pom.xml
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/ClientMapper.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/Alert.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/model/AlertTest.java
cccm-backend/cccm-role-sync/pom.xml
cccm-backend/pom.xml

Move to Version 21

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java

Dynamically Return Form Id

---

cccm-backend/cccm-api/src/main/resources/cccm-api.yaml

Adding new field

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/CompleteFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/DeleteFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/EditFormTest.java

Add and implement created By Idir 

Created By Idir 

---

cccm-backend/cccm-api/src/main/resources/configs/sara_validation_config.json

Adding all required fields to sara validation

---

cccm-frontend/src/components/common/templateClientProfile.json

- Remove court tab from client profile
Manually

Remove court tab

---

cccm-backend/cccm-api/src/main/resources/configs/overall_validation_config.json
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/validation/ValidateACUTETest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/validation/ValidateOVERALLTest.java

Add overall config

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/main/resources/configs/stable_validation_config.json
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/validation/ValidateSTABLETest.java

Adding Stable Validation

---

cccm-frontend/src/components/DashboardPOView.vue
cccm-frontend/src/components/Header.vue

Use Keycloak name if present and reverse name
Make dashboard links conditional

PO Dashboard Update Name Logic and Dashboard Link Logic

---

cccm-frontend/package-lock.json
cccm-frontend/package.json
cccm-frontend/src/components/form.api.ts

Add error message on axios requests

Adding Error Message

---

cccm-frontend/src/components/DashboardPOView.vue
cccm-frontend/src/components/DashboardSupervisorView.vue
cccm-frontend/src/components/common/FormioClientSearch.vue
cccm-frontend/src/components/common/templateClientSearch.json
cccm-frontend/src/components/common/templateSidePanel.json

Community location reference change

Fix Client Search, Order Info and Name in Header

---

cccm-frontend/src/components/DashboardSupervisorView.vue
cccm-frontend/src/components/common/FormioClientSearch.vue

Adding Clear Reload and Progress

---

.github/dependabot.yml

Add Dependabot Weekly Check

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/UserMapper.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-frontend/src/components/DashboardSupervisorView.vue

Add SEN Column

---

cccm-backend/cccm-api/src/main/resources/configs/sara_validation_config.json

Update SARA Validation Config

---

cccm-backend/cccm-api/src/main/resources/configs/acute_validation_config.json
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/validation/ValidateACUTETest.java

Update Validation from form changes

Update Acute Validation

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/UserMapper.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/UserDataService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/UserDataServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/user/UserApiImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/user/GetPOListTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/user/GetPoListTest.java
cccm-frontend/src/components/DashboardPOView.vue
cccm-frontend/src/components/DashboardSupervisorView.vue
cccm-frontend/src/components/common/templateClientSearch.json
cccm-frontend/src/components/form.api.ts

PO Dash Updates

---

cccm-frontend/src/components/form.api.ts
cccm-frontend/src/stores/store.js

Remove locationId param

---

cccm-backend/cccm-api/src/main/resources/configs/sara_validation_config.json
cccm-frontend/src/components/common/FormioClientSearch.vue
cccm-frontend/src/components/common/templateClientSearch.json

Update Validation Config

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-frontend/src/assets/css/styles.css
cccm-frontend/src/components/DashboardSupervisorView.vue
cccm-frontend/src/components/common/FormioClientSearch.vue

Apply clouring logic to supervisor dashboard

Add Column Colouration

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/client/ClientsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/UserMapper.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/ClientProfile.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ObridgeClientService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/UserDataServiceImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/GetClientPhotoTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/model/ClientProfileTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientDetailsTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientFormSearchTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientPhotoTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientProfileTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/GetClientFormSummaryTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/CloneFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/CompleteFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/DeleteFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/EditFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/user/GetPOListTest.java

Add po list implementation
Update data type to string (Removes timestamp)

Add PO List Implementation, Fix Data data type

---

cccm-frontend/src/assets/css/layout.css
cccm-frontend/src/components/form/FormRenderer.vue
cccm-frontend/src/components/form/formSections/FormNavigation.vue

- Fixed form load section display issue
Manually

Fixed form load section display issue

---

cccm-backend/cccm-api/src/main/resources/cccm-api.yaml

Add new field

---

cccm-frontend/src/components/CmpForm.vue
cccm-frontend/src/components/RNAList.vue
cccm-frontend/src/components/common/FormioButtonGroupSide.vue
cccm-frontend/src/components/common/templateButtonGroupSide.json
cccm-frontend/src/components/form/FormRenderer.vue

Added logic to show/hide print btn

---

cccm-frontend/src/assets/css/overrides.css

Add some ui fixes

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/ClientFormAnswers.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/CompleteFormInput.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ObridgeClientService.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/CompleteFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/EditFormTest.java

Re-Add Fields

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientFormSearchTest.java

For Search Feature Flag Bug

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/dashboard/DashboardsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/UserDataService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/UserDataServiceImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/dashboard/GetSupervisorDashboardDetailsTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/user/GetSupervisorDashboardDetailsTest.java
cccm-frontend/src/components/DashboardSupervisorView.vue
cccm-frontend/src/components/form.api.ts

Fix Dashboard Details

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java

Fix Missing Colon in Text

---

cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-frontend/src/components/trendanalysis/ChartFilter.vue

CBCCM-652 - Bug fixes

---

cccm-frontend/src/components/common/FormioClientSearch.vue

- Code cleanup
- [X Refactoring / Documentation

Removed token

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/ClientMapper.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/ClientProfile.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/model/ClientProfileTest.java

Add the next due date to client profile

Add Next Due Date

---

cccm-frontend/src/components/common/templateSidePanel.json

- CBCCCM-766: Sources Contacted - CRNA/SARA - Move Up

Reposition sources contacted

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/main/resources/configs/sara_validation_config.json

Remove Intervention Validation SARA

---

cccm-backend/cccm-api/pom.xml
cccm-backend/cccm-role-sync/pom.xml
cccm-backend/pom.xml

Update backend version

---

cccm-frontend/src/components/common/FormioClientSearch.vue

- CBCCCM-665: Data mapping issue in client search expanded row

Fixed the data mapping issue in client search expanded view

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java

Remove Supervision Level From Log

---

cccm-backend/cccm-api/src/main/resources/configs/crna_validation_config.json

Add Sources Contacted to validation

Sources Contacted Validation 

---

cccm-backend/cccm-api/pom.xml

Add OTEL For Enriched Logs

---

cccm-backend/cccm-api/src/main/resources/cccm-api.yaml

Add intervention validation payload

---

cccm-frontend/src/components/form/FormRenderer.vue

- CBCCCM-763: CRNA/SARA Validation - Intervention Type and Description Fields

Field renamed

---

cccm-backend/cccm-api/pom.xml
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/service/UpdateForm.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/validation/ValidationType.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ValidationService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ValidationServiceImpl.java
cccm-backend/cccm-api/src/main/resources/configs/crna_validation_config.json
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/CloneClientFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/CompleteFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/CreateACUTEFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/DeleteClientFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/DeleteInterventionsExceptUsingPUTTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/GetClientFormAnswersForSectionAndQuestionUsingGETTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/GetClientFormAnswersUsingGETTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/GetClientFormSummaryUsingGETTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/LinkFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/SaveClientFormAnswersUsingPUTTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/SearchClientCommentsUsingPOSTTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/SearchClientInterventionsUsingPOSTTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/SearchClientResponsivitiesUsingPOSTTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/UpcertResponsivitiesTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/CompleteFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/EditFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/validation/ValidateCRNATest.java
cccm-backend/cccm-api/src/test/resources/configs/crna_validation_config.json
cccm-backend/cccm-api/src/test/resources/configs/sara_validation_config.json
cccm-backend/cccm-role-sync/src/main/java/ca/bc/gov/open/jag/service/CSSSSOApiService.java

Adding intervention validation

Adding Validation For Intervention Type

---

cccm-frontend/src/components/PrintView.vue
cccm-frontend/src/components/RNAList.vue

- CBCCCM-782: Print Case Plan missing ratings

Removed Location, fixed the rating display issue

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ValidationServiceImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml

Fix null keys
Fix incorrect application of pattern

Fix Null Keys 

---

cccm-frontend/src/components/DashboardPOView.vue

- CBCCCM-756: Client Dashboard "Due Next" and "Due Date" fields not functional

fixed dueDate sorting issue, add color to dueNext

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/Keys.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/CloneFormTest.java

Strip all existing ID's from answers

Intervention Clone Issue

---

cccm-frontend/src/components/ClientRecord.vue
cccm-frontend/src/components/DashboardPOView.vue
cccm-frontend/src/components/common/templateClientProfilePO.json

- CBCCCM-809: Remove Outstanding Warrants

Removed warrants display

---

.github/workflows/backend-promote-image-to-env.yml
.github/workflows/frontend-promote-image-to-env.yml
.github/workflows/role-sync-promote-image-to-env.yml

- Forgot the golddr logins in the promote env 
- [x ] Bug fix (non-breaking change which fixes an issue)
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have made corresponding changes to the documentation
- [x ] New and existing unit tests pass locally with my changes

added golddr logins

---

cccm-frontend/src/main.ts

- CBCCCM-774: Supervision Rating tab doesn't load immediately upon being selected

Removed the dataRefreshSectionIndex for CRNA

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/UserMapper.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/PODashboard.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/user/GetPoDashboardTest.java

UCMP PO Dashboard

---

cccm-frontend/src/components/trendanalysis/ChartFilter.vue
cccm-frontend/src/components/trendanalysis/TrendChart.vue

- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] I have performed a self-review of my own code

CBCCCM-784 Trend Analysis is blank upon first viewing

---

cccm-frontend/src/components/form/formSections/FormNavigation.vue

- CBCCCM-813: Navigation isn't following user on RNA

Fixed the nav issue observed in edge

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/dashboard/DashboardsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/resources/application.properties
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientFormSearchTest.java

CBCCCM-801 temporary sort on created date
CBCCCM-728 fix request parameter swapped

Sort RNA List and Fix SCM and PCM Request

---

cccm-frontend/src/components/PrintView.vue

- CBCCCM-822: Reassessment Comments not showing on Print Form

Fixed the issue where Reassessment comments not showing.

---

cccm-backend/cccm-api/src/main/resources/application.properties

Type Switch

---

cccm-backend/cccm-api/src/main/resources/application.properties

Remove TLS

---

cccm-backend/cccm-api/src/main/resources/application.properties

Re-add tls

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/UserMapper.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/SupervisorDashboard.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/resources/application.properties
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientFormSearchTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/user/GetSupervisorDashboardTest.java

CBCCCM-729: Implement the sen column

Add SEN(SENT) Column 

---

cccm-backend/cccm-role-sync/src/main/java/ca/bc/gov/open/jag/service/RoleSyncServiceImpl.java

Add Null Check 

---

cccm-backend/cccm-role-sync/src/main/java/ca/bc/gov/open/jag/Keys.java
cccm-backend/cccm-role-sync/src/main/java/ca/bc/gov/open/jag/service/RoleSyncServiceImpl.java

Spelling Update

---

cccm-backend/cccm-role-sync/src/main/java/ca/bc/gov/open/jag/service/RoleSyncServiceImpl.java

Refer to Keys

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-role-sync/src/main/java/ca/bc/gov/open/jag/service/RoleSyncServiceImpl.java

Update For Title in Validation

---

cccm-backend/cccm-api/src/main/resources/application.properties

Add TLS Configs

---

cccm-frontend/src/components/trendanalysis/ChartFilter.vue
cccm-frontend/src/components/trendanalysis/TrendChart.vue

The interventions popup once selected can’t be unselected.

---

cccm-frontend/src/stores/store.js

Fixed the userGroup issue if user is in multiple groups

---

cccm-backend/cccm-role-sync/src/main/java/ca/bc/gov/open/jag/service/RoleSyncServiceImpl.java

Add Logging

---

cccm-backend/cccm-role-sync/src/main/java/ca/bc/gov/open/jag/service/RoleSyncServiceImpl.java

Truncate Users Name to Reduce Misses

---

cccm-backend/cccm-role-sync/src/main/java/ca/bc/gov/open/jag/service/RoleSyncServiceImpl.java

Update Federated Identity Check

---

cccm-backend/cccm-role-sync/src/main/java/ca/bc/gov/open/jag/service/RoleSyncServiceImpl.java

Add mapping for users with missing idp

Add additional mapping logic

---

cccm-backend/cccm-role-sync/src/main/java/ca/bc/gov/open/jag/service/RoleSyncServiceImpl.java

Add additional char to sso request

One More Char

---

cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-frontend/src/components/trendanalysis/ChartFilter.vue

- [ x] Bug fix (non-breaking change which fixes an issue)

Trend Analysis - Adding Min/Max range as a separate attribute in the API

---

cccm-backend/cccm-api/src/main/resources/application.properties

Remove TLS Temproarily

---

cccm-backend/cccm-api/src/main/resources/application.properties

Re-Add TLS Configs

---

cccm-backend/cccm-api/pom.xml
cccm-backend/cccm-api/src/main/resources/application.properties
cccm-backend/cccm-role-sync/pom.xml
cccm-backend/pom.xml
cccm-frontend/package.json

Update Properties and Version 1.0.0

---

cccm-backend/cccm-api/pom.xml
cccm-backend/cccm-role-sync/pom.xml
cccm-backend/pom.xml

Move to SNAPSHOT

---

cccm-frontend/src/components/common/FormioSidePanel.vue
cccm-frontend/src/components/common/templateSidePanel.json

…updateDate update logic
- CBCCCM-731: Business API Implementation of 'form_updated_date' procedure calls

UpdateDate logic update in the frontend

---

cccm-backend/cccm-api/pom.xml
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-role-sync/pom.xml
cccm-backend/pom.xml

Add Null Checks 

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientFormSearchTest.java
cccm-frontend/src/components/RNAList.vue

CBCCCM-850: add new field and map in front end

Add OSU Update Date

---

cccm-frontend/src/components/ClientRecord.vue
cccm-frontend/src/main.ts
cccm-frontend/src/stores/store.js

- CBCCCM-853: Make Trend Analysis configurable in Keycloak

Added logic to handle show-trend role

---

cccm-backend/cccm-api/pom.xml
cccm-backend/cccm-role-sync/pom.xml
cccm-backend/pom.xml
cccm-frontend/package.json

Version 1.0.1 Frontend and Backend

Version 1.0.1

---

cccm-frontend/src/components/Footer.vue

- Update frontend build version

Update the build version to 'Release 1.0.1 (build 1)'

---

cccm-backend/cccm-api/pom.xml
cccm-backend/cccm-role-sync/pom.xml
cccm-backend/pom.xml

1.0.2-SNAPSHOT

---

cccm-backend/cccm-api/src/main/resources/configs/acute_validation_config.json
cccm-backend/cccm-api/src/main/resources/configs/overall_validation_config.json
cccm-backend/cccm-api/src/main/resources/configs/stable_validation_config.json
cccm-backend/cccm-api/src/main/resources/configs/static99r_validation_config.json
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/validation/ValidateACUTETest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/validation/ValidateOVERALLTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/validation/ValidateSTABLETest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/validation/ValidateSTAT99Test.java

Add sources contacted to validation

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ValidationServiceImpl.java

Update Static-99R 

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/CompleteFormInput.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java

Add logged in location to completion

---

cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-frontend/src/components/trendanalysis/CommentsAndInterventionsTable.vue
cccm-frontend/src/components/trendanalysis/TrendChart.vue

Trend Analysis - Comment and Intervention Tooltip Fixes

---

cccm-frontend/src/components/form/formSections/FormSummary.vue

- Show section level intervention plans in Summary view

Update to support new STABLE requirements

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/util/UpdateDateComparator.java
cccm-frontend/src/components/RNAList.vue

Logic to assign and sort date: Update Date -> Complete Date -> Created Date

Add date logic to display and sort

---

cccm-backend/cccm-api/src/main/resources/configs/sara_validation_config.json

Validation Bug

---

cccm-backend/cccm-api/pom.xml
cccm-backend/cccm-role-sync/pom.xml
cccm-backend/pom.xml
cccm-frontend/package.json

Version 1.0.2

---

cccm-frontend/src/components/Footer.vue

- Updated build version to 1.0.2

Updated the build version to 1.0.2

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/resources/configs/overall_validation_config.json

Patch Null Pointer

---

cccm-backend/cccm-api/pom.xml
cccm-backend/cccm-role-sync/pom.xml
cccm-backend/pom.xml

Version 1.0.3-SNAPSHOT

---

cccm-backend/cccm-api/src/main/resources/configs/overall_validation_config.json
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/validation/ValidateOVERALLTest.java

Add Overall Validation

---

cccm-backend/cccm-api/src/main/resources/configs/crna_validation_config.json

CBCCCM-874 fix validation issue

Validation Fix

---

cccm-frontend/src/components/PrintView.vue
cccm-frontend/src/components/form/formSections/FormSummary.vue

- CBCCCM-875: Print Function Not Matching Intervention Plan in Case Plan (showing D for specific factor instead of comments)

Fixed the 'specific factor'

---

cccm-frontend/src/components/Header.vue

Update lengths
Should be a config but that can be later

Add Longer Timeout

---

cccm-backend/cccm-api/src/main/resources/application.properties

Add increased read timeout to obridge request

---

cccm-backend/cccm-api/pom.xml
cccm-backend/cccm-role-sync/pom.xml
cccm-backend/pom.xml

Version 1.0.4-SNAPSHOT

---

cccm-frontend/src/components/PrintView.vue

- CBCCCM-875: Print Function Not Matching Intervention Plan in Case Plan (showing D for specific factor instead of comments)

Adjustment toward print view

---

cccm-frontend/src/components/PrintView.vue

- CBCCCM-875: Print Function Not Matching Intervention Plan in Case Plan (showing D for specific factor instead of comments)

Added space between each column

---

cccm-frontend/nginx.conf

maintenance page

---

cccm-backend/cccm-api/pom.xml
cccm-backend/cccm-role-sync/pom.xml
cccm-backend/pom.xml
cccm-frontend/src/components/Footer.vue

Version 1.0.3

---

cccm-frontend/src/components/CmpForm.vue

- Fix the create Overall btn behavior

Fixed the 'Overall' creation btn behavior

---

cccm-backend/cccm-api/pom.xml
cccm-backend/cccm-role-sync/pom.xml
cccm-backend/pom.xml

Version 1.0.5 SNAPSHOT

---

cccm-frontend/src/components/trendanalysis/ChartFilter.vue
cccm-frontend/src/components/trendanalysis/TrendChart.vue

- CBCCCM-893: Refactor Trend Analysis - make Y-axis data driven

Added more filter options, redesigned the datapoint popup

---

cccm-frontend/src/components/common/FormioButtonGroupSubmit.vue
cccm-frontend/src/components/form/FormRenderer.vue
cccm-frontend/src/main.ts

- CBCCCM-894: Remove Multiple Click Function on Submit Form Button

Fixed the code to prevent double clicking

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/ClientFormSearchUsingGETTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientFormSearchTest.java

Adding most recent functionality

---

cccm-frontend/src/components/trendanalysis/ChartFilter.vue
cccm-frontend/src/components/trendanalysis/TrendAnalysisView.vue
cccm-frontend/src/components/trendanalysis/TrendChart.vue

- CBCCCM-893: Refactor Trend Analysis - make Y-axis data driven

Make chart yaxis data-driven

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/Keys.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/main/resources/configs/clone_config.json

SO Overall to SMO Overall

---

cccm-frontend/src/components/trendanalysis/ChartFilter.vue
cccm-frontend/src/components/trendanalysis/TrendAnalysisView.vue
cccm-frontend/src/components/trendanalysis/TrendChart.vue
cccm-frontend/src/stores/trendstore.js

- Fixed the trend intervention display issue

Fixed the intervention display issue

---

cccm-backend/cccm-api/src/main/resources/configs/stable_validation_config.json
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/validation/ValidateSTABLETest.java

Update Stable Validation

---

cccm-frontend/src/components/trendanalysis/CommentsAndInterventionsTable.vue
cccm-frontend/src/components/trendanalysis/DataView.vue

- CBCCCM-807: Trend Analysis: Graph button too dark
- CBCCCM-904: Trend 'Comments & Intervention' view table footer needs update

Feature/807 904 trend UI updates

---

cccm-backend/cccm-api/src/main/resources/configs/stable_validation_config.json
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/validation/ValidateSTABLETest.java

Validation Update

---

cccm-frontend/src/components/form/FormRenderer.vue

- CBCCCM-908: UAT - Static-99R Results

When form is in expanded view, show error if validation failed

---

.github/dependabot.yml

Update dependabot.yml reduce dependabot pr

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/ClientFormSearchUsingGETTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/GetClientFormSummaryUsingGETTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientFormSearchTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/GetClientFormSummaryTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/CompleteFormTest.java

UPdate spec and associated changes

---

cccm-backend/cccm-api/src/main/resources/configs/overall_validation_config.json
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/validation/ValidateOVERALLTest.java

Update Overall Validation

---

cccm-frontend/src/components/PrintView.vue
cccm-frontend/src/components/RNAList.vue
cccm-frontend/src/components/form/formSections/FormSMOOverallBPSection.vue
cccm-frontend/src/components/form/formSections/FormSummary.vue
cccm-frontend/src/main.ts

- CBCCCM-913: UAT SMO Overall Results

Show BP section in table format in summary and print view

---

cccm-frontend/src/components/PrintView.vue

- Move BP section at the end of the print view

Move BP section at the end

---

cccm-frontend/src/assets/css/overrides.css

Adjust the tooltip css

---

cccm-backend/cccm-api/src/main/resources/configs/overall_validation_config.json
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/validation/ValidateOVERALLTest.java

Remove validation that is not required

Overall Validation Updates

---

cccm-backend/cccm-role-sync/src/main/java/ca/bc/gov/open/jag/Keys.java
cccm-backend/cccm-role-sync/src/main/java/ca/bc/gov/open/jag/model/RoleGroupEnum.java
cccm-backend/cccm-role-sync/src/main/java/ca/bc/gov/open/jag/service/RoleSyncServiceImpl.java
cccm-backend/cccm-role-sync/src/test/java/ca/bc/gov/open/jag/service/RoleSyncServiceTest.java

Update role sync add admin comm

---

cccm-frontend/src/components/CmpForm.vue
cccm-frontend/src/components/Header.vue
cccm-frontend/src/components/RNAList.vue
cccm-frontend/src/main.ts
cccm-frontend/src/stores/store.js

- CBCCCM-931: Add Can View On RNA List

Added support to admin-comm group

---

cccm-frontend/src/components/form/FormRenderer.vue
cccm-frontend/src/stores/autoSaveStore.js

- CBCCCM-932: Avoid autosave upon form load

Console log cleanup

---

cccm-frontend/src/components/common/FormioSidePanel.vue
cccm-frontend/src/components/form/FormRenderer.vue
cccm-frontend/src/main.ts
cccm-frontend/src/stores/autoSaveStore.js

- CBCCCM-932: Avoid autosave upon form load

Fixed the autosave payload issue

---

cccm-backend/cccm-api/src/main/resources/configs/stable_validation_config.json

Update validation CBCCCM-937

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/Keys.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ValidationServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/util/FormUtils.java

Add CRNA, SATA Overall Ratings 

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/Keys.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/util/FormUtils.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientFormSearchTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/util/form/RatingToIntegerTest.java

Map highest rating
Add rating level mappings
Update and Add Tests 

Map Highest Rating  

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/Keys.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientFormSearchTest.java

Remove Acute from level logic 

Remove acute from mapping process

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/util/FormUtils.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientFormSearchTest.java

Update mapping
Remove static/stable

Update to Return High/Medium/Low

---

cccm-frontend/src/components/form/FormRenderer.vue

- CBCCCM-954: Delete Form Button Missing

Fixed the 'Edit' btn logic

---

cccm-frontend/src/components/form/FormRenderer.vue

- CBCCCM-954: Delete Form Button Missing

Fixed the page refresh when 'edit' button clicked

---

cccm-frontend/src/components/form/formSections/FormSummary.vue

- CBCCCM-956: Include full description for Static Rating

Added answer desc to the summary view

---

cccm-frontend/src/components/common/templateFormInfo.json

Updated typo

---

cccm-frontend/src/components/RNAList.vue
cccm-frontend/src/components/common/templateFormInfo.json

- CBCCCM-942: Updated date not showing when viewing a form instance

Fixed the logic to show updatedDate

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/Keys.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java

Add answers description

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/Keys.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/util/FormUtils.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/client/GetClientAddressSearchTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/util/form/RatingToIntegerTest.java

- Add aditional codes
- Clear ratings at beginning 

Add Updated Mappings

---

cccm-frontend/src/components/RNAList.vue
cccm-frontend/src/components/form/FormRenderer.vue

- CBCCCM-959: Stable Interventions Not Saving
- Fixed the RNA List rating column color

Fixed the intervention updating issue; fixed the color on rating display

---

cccm-backend/cccm-api/pom.xml
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/CompleteFormInput.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/CompleteFormTest.java
cccm-backend/cccm-role-sync/pom.xml
cccm-backend/pom.xml

Update completed form and increment version for release

Update version and Add required field

---

cccm-frontend/src/components/Footer.vue

- Updated the build version to 1.1.0

Updated the build version

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/EditFormTest.java
cccm-frontend/package.json

Add missing child form completion

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java

Refine code

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/EditFormTest.java

Add change to capture existing value

Add change to capture existing value

---

cccm-backend/cccm-api/pom.xml
cccm-backend/cccm-role-sync/pom.xml
cccm-backend/pom.xml

Version update

---

cccm-frontend/public/config.js
cccm-frontend/src/components/CmpForm.vue
cccm-frontend/src/components/RNAList.vue

- CBCCCM-974: Remove "add SMO-Overall-CMP" button from CRNA form

Remove the SMO-Overall-CMP button

---

cccm-frontend/src/components/CmpForm.vue
cccm-frontend/src/components/RNAList.vue
cccm-frontend/src/main.ts
cccm-frontend/src/stores/store.js

- CBCCCM-978: Remove SMO Forms Feature Flag Code

Removed SMO feature flag

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/Keys.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/ClientFormSearchTest.java

Remove smo role override

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java

Remove temp logs

---

cccm-backend/cccm-api/pom.xml
cccm-backend/cccm-role-sync/pom.xml
cccm-backend/pom.xml
cccm-frontend/package.json
cccm-frontend/src/components/Footer.vue

Version 1.1.2

---

cccm-backend/README.md

Update Add Version Instruction

---

cccm-backend/cccm-role-sync/src/main/java/ca/bc/gov/open/jag/service/RoleSyncServiceImpl.java

Fix search to exact search only

---

cccm-frontend/src/components/PrintView.vue
cccm-frontend/src/components/form/formSections/FormSummary.vue

- CBCCCM-1042: Print Function Losing Style Formatting

Fix print formatting on comment fields

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/Keys.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ValidationService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ValidationServiceImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/main/resources/configs/cmrp_validation_config.json
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/ClientFormSearchUsingGETTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/CloneClientFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/CreateCmrpFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/form/GetClientFormSummaryUsingGETTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/GetClientFormSummaryTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/CompleteFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/CreateFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/EditFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/validation/ValidateCMRPTest.java

- Create CMRP
- Complete
- Validate (No complete rules applied)

Adding CMRP create/complete/validation functionality

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/dashboard/DashboardsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/ClientMapper.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/UserMapper.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/CentreDashboard.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/ClientProfile.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ObridgeClientService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/UserDataService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/UserDataServiceImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/dashboard/GetCentreDashboardTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/user/GetCentreDashboardTest.java
cccm-frontend/package-lock.json
cccm-frontend/public/config.js

Add search, additional client details and My Dahsboard

---

cccm-backend/Dockerfile
cccm-backend/cccm-role-sync/Dockerfile.rolesync

Update docker files

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/ClientMapper.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientDataServiceImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/client/GetClientFormSummaryTest.java

Adding fields (Custody Location, population Designations)

---

cccm-frontend/src/components/common/FormioSidePanel.vue
cccm-frontend/src/components/common/templateSidePanel.json
cccm-frontend/src/components/form/FormRenderer.vue

- CCCM-1014: Community Supports Card on Custody-CMRP

Community Supports panel on CMRP form

---

cccm-frontend/src/components/common/templateSidePanel.json

- CBCCCM-993: Front-end: Custody Order details on Custody-CMRP

Custody Order Panel

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/UserMapper.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/CentreDashboard.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/dashboard/GetCentreDashboardTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/user/GetCentreDashboardTest.java

Add alert counts

---

cccm-frontend/src/components/dashboard/DashboardITRPView.vue

- CBCCCM-1023: My Centre Dashboard

Filter alerts on My Centre Dashboard

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ValidationServiceImpl.java
cccm-backend/cccm-api/src/main/resources/configs/clone_config.json
cccm-backend/cccm-api/src/main/resources/configs/cmrp_validation_config.json
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/validation/ValidateCMRPTest.java

- Update Validation Config
- Add clone config

Add validation and clone configs

---

cccm-frontend/src/components/common/templateSidePanel.json

- CBCCCM-1071: Updating the Client Details, Community Supports, Custody Order Sections in the Custody CMRP Form

update CMRP form side panels

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/ClientDates.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ObridgeClientService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ValidationService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ValidationServiceImpl.java
cccm-backend/cccm-api/src/main/resources/configs/cmrp_basic_validation_config.json
cccm-backend/cccm-api/src/main/resources/configs/cmrp_validation_config.json
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/validation/ValidateCMRPTest.java
cccm-frontend/public/config.js

- Add Validation Logic to submit

Add Validation Logic

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/CodeTableMapper.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/LocationMapper.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/UserDataService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/UserDataServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/user/UserApiImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/user/GetDefaultLocationTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/user/GetLocationsTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/user/GetUserDefaultLocationTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/user/GetUserLocationsTest.java

Location Code

---

cccm-frontend/src/assets/css/overrides.css
cccm-frontend/src/components/Header.vue
cccm-frontend/src/components/dashboard/DashboardITRPView.vue
cccm-frontend/src/stores/store.js

- CBCCCM-1067: My Centre Dashboard Should Only Show When In Custody Centre Location

show my centre dashboard only for custody centre locations

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/Keys.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java

Add log comments

---

cccm-frontend/src/assets/css/styles.css
cccm-frontend/src/components/Header.vue

Fix Logout Link

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/mapper/ClientMapper.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/ClientProfile.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/WarrantType.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-frontend/src/components/common/templateSidePanel.json

- Add warrant types list
- Display all types

Warrant Type Update

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ValidationService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ValidationServiceImpl.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/validation/ValidateCMRPTest.java

- Update CMRP Validation Intervention Requirement

Update CMRP Validation

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java

Update log comment

---

cccm-frontend/src/components/CmpForm.vue
cccm-frontend/src/components/common/templateSidePanel.json

- CBCCCM-1079: Unable to edit Unlocked Custody CMRP another ITRP user has created

edit unlocked custody-cmrp form

---

cccm-frontend/src/components/common/templateFormInfo.json

- CBCCCM-1093: Change Custody Location to Office Location on Custody-CMRP form

Custody location label fix for CMRP form

---

cccm-frontend/src/components/CmpForm.vue
cccm-frontend/src/components/Header.vue
cccm-frontend/src/components/RNAList.vue
cccm-frontend/src/components/form/FormRenderer.vue
cccm-frontend/src/router/index.ts
cccm-frontend/src/stores/store.js

- CBCCCM-1066: My Team Dashboard not working

My Team dashboard fix

---

cccm-frontend/src/components/dashboard/DashboardPOView.vue
cccm-frontend/src/components/dashboard/DashboardSupervisorView.vue
cccm-frontend/src/stores/store.js

- CBCCCM-1066: My Team Dashboard not working

Hide dashboards based on active location

---

cccm-frontend/src/components/dashboard/DashboardPOView.vue
cccm-frontend/src/components/dashboard/DashboardSupervisorView.vue
cccm-frontend/src/stores/store.js

Reverts bcgov/jag-community-corrections-case-management#944

Revert "Hide dashboards based on active location"

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java

Add new line to comments

---

cccm-frontend/src/components/Header.vue
cccm-frontend/src/components/dashboard/DashboardPOView.vue
cccm-frontend/src/components/dashboard/DashboardSupervisorView.vue
cccm-frontend/src/stores/store.js

- CBCCCM-1066: My Team Dashboard not working - CMRP Testing

Hide PO dashboard for institution locations

---

.github/workflows/backend-build-push.yml
.github/workflows/frontend-build-push.yml
.github/workflows/role-sync-push.yml

took out dash

---

cccm-frontend/src/components/common/templateSidePanel.json

- CBCCCM-1096: Front-end: rename Client details labels for Current active location and Institution 

client details label rename

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java

- Add formatting to log comments

Update log comments

---

cccm-frontend/src/stores/store.js

- CBCCCM-1066: My Team Dashboard not working

Show PO dash for ITRP users

---

cccm-frontend/package-lock.json
cccm-frontend/package.json
cccm-frontend/src/components/dashboard/DashboardITRPView.vue
cccm-frontend/src/components/dashboard/util/DashboardDueDateLegend.vue
cccm-frontend/src/components/dateUtils.ts

- CBCCCM-1098: My Centre Dashboard Loading Issues - VIRCC and FRCC

Added date-fns lib; fixed the date related issue

---

cccm-frontend/src/components/trendanalysis/TrendChart.vue

Fixes [https://github.com/bcgov/jag-community-corrections-case-management/security/code-scanning/1](https://github.com/bcgov/jag-community-corrections-case-management/security/code-scanning/1)
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

Fix code scanning alert no. 1: Inefficient regular expression

---

cccm-frontend/src/components/RNAList.vue
cccm-frontend/src/components/form/FormRenderer.vue

- CBCCCM-1111: Custody CMRP - Unable to Edit Another User Unlocked Form;

Applied the new business rules toward CMRP edit/complete/clone

---

cccm-backend/cccm-api/pom.xml
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-role-sync/pom.xml
cccm-backend/pom.xml
cccm-frontend/package-lock.json
cccm-frontend/package.json

Add flag to client form summary, Update to new feature version

---

cccm-frontend/src/components/RNAList.vue
cccm-frontend/src/main.ts
cccm-frontend/src/stores/store.js

- CBCCCM-1122: Custody CMRP Production : Remove CMRP Feature Flag;

Removing the CMRP feature flag

---

cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/model/data/CompleteFormInput.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ValidationService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ValidationServiceImpl.java
cccm-backend/cccm-api/src/main/resources/cccm-api.yaml
cccm-backend/cccm-api/src/main/resources/configs/case_plan_validation_config.json
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/CompleteFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/clientForm/EditFormTest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/validation/ValidateCRNATest.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/validation/ValidateOVERALLTest.java

- Add validaiton and validation bypass

Add CRNA and SO Overall Validation

---

cccm-frontend/src/components/Footer.vue
cccm-frontend/src/components/dashboard/DashboardITRPView.vue

- CBCCCM-1123: Replace ITRP alert with CRP1;

Label change

---

cccm-backend/cccm-api/pom.xml
cccm-backend/cccm-api/src/main/resources/application.properties
cccm-backend/cccm-role-sync/pom.xml
cccm-backend/pom.xml

Update version, Resolve Erro from Quarkus bug

---

cccm-backend/cccm-api/pom.xml
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/form/FormsApiImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ClientFormSaveServiceImpl.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ValidationService.java
cccm-backend/cccm-api/src/main/java/ca/bc/gov/open/jag/api/service/ValidationServiceImpl.java
cccm-backend/cccm-api/src/test/java/ca/bc/gov/open/jag/api/service/dataservice/validation/ValidateOVERALLTest.java

- update intervention validation

Intervention validation updates

---

cccm-backend/cccm-role-sync/src/main/java/ca/bc/gov/open/jag/service/RoleSyncServiceImpl.java

Add additional logging for debugging

---

cccm-backend/cccm-api/src/main/resources/application.properties
cccm-backend/cccm-role-sync/src/main/java/ca/bc/gov/open/jag/Keys.java
cccm-backend/cccm-role-sync/src/main/java/ca/bc/gov/open/jag/model/RoleGroupEnum.java
cccm-backend/cccm-role-sync/src/main/java/ca/bc/gov/open/jag/service/RoleSyncServiceImpl.java
cccm-backend/cccm-role-sync/src/test/java/ca/bc/gov/open/jag/service/RoleSyncServiceTest.java
cccm-frontend/public/config.js

- Migrate to Cornet keyclaok
- Add JAM Roles to RoleSync Service

Migrate to Cornet Keycloak
